### ISSUE TITLE
Summit build with Ubuntu 20.04 / libboost numpy version?

### ISSUE THREAD

**Issue by PelleNordqvist** [AdaCompNUS/summit#21]
Hello Summit team! I was curious about this project and wanted to test the traffic model,
to see I I can tweak it to my needs. Therefore I think I need to compile it from ground up.
I am using ubuntu 20.04 and I can compile the latest carla, but when using the Summit branch and the instructions here
https://adacompnus.github.io/summit-docs/getting_started/setting_up/
I got stuck on boost numpy dependency.
Summit installs boost 1.72.0 which contains libboost_numpy38.a
but it seems the build process is looking for version 27:

> make PythonApi
....
building 'carla.libcarla' extension
ccache clang-7 -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-W1mjrO/python2.7-2.7.18=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Idependencies/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/include/python2.7 -c source/libcarla/libcarla.cpp -o build/temp.linux-x86_64-2.7/source/libcarla/libcarla.o -isystem dependencies/include/system -fPIC -std=c++14 -O3 -Werror -Wall -Wextra -Wpedantic -Wno-self-assign-overloaded -Wdeprecated -Wno-shadow -Wuninitialized -Wunreachable-code -Wpessimizing-move -Wold-style-cast -Wnull-dereference -Wduplicate-enum -Wnon-virtual-dtor -Wheader-hygiene -Wconversion -Wfloat-overflow-conversion -Wsign-conversion -Wno-unused-parameter -DBOOST_ERROR_CODE_HEADER_ONLY -DLIBCARLA_WITH_PYTHON_SUPPORT -DLIBCARLA_IMAGE_WITH_PNG_SUPPORT=false
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-W1mjrO/python2.7-2.7.18=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-W1mjrO/python2.7-2.7.18=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC build/temp.linux-x86_64-2.7/source/libcarla/libcarla.o -Ldependencies/lib -L/usr/lib/gcc/x86_64-linux-gnu/7 -o build/lib.linux-x86_64-2.7/carla/libcarla.so /opt/summit/PythonAPI/carla/dependencies/lib/libcarla_client.a /opt/summit/PythonAPI/carla/dependencies/lib/librpc.a /opt/summit/PythonAPI/carla/dependencies/lib/libboost_filesystem.a /opt/summit/PythonAPI/carla/dependencies/lib/libRecast.a /opt/summit/PythonAPI/carla/dependencies/lib/libDetour.a /opt/summit/PythonAPI/carla/dependencies/lib/libDetourCrowd.a /opt/summit/PythonAPI/carla/dependencies/lib/libboost_python27.a /opt/summit/PythonAPI/carla/dependencies/lib/libboost_numpy27.a -ldl -lm -lpthread -lrt -lbz2 -lexpat -ljpeg -ltiff /usr/lib/gcc/x86_64-linux-gnu/7/libstdc++.a
x86_64-linux-gnu-gcc: error: /opt/summit/PythonAPI/carla/dependencies/lib/libboost_numpy27.a: No such file or directory

**Comment by LeeYiyuan** [comment]
Hi @PelleNordqvist , thanks for raising this issue! When we made SUMMIT, Python 2 was on its way to deprecation in Ubuntu 18.04, so it was unclear how things would work on Ubuntu 20.04.

If you run `make PythonApi.3` it will only build the Python3 versions of the PythonAPI. This should work, if you are not using Python 2 anymore.

**Comment by PelleNordqvist** [comment]
Hello Lee, thanks for your quick response!
As for python2, I would not miss it at all :) You could make python3 default if you asked me.
I stumbled on a new error when trying your advice, see below.
Are you expecting a special version of python3? 3.6, 3.7, 3.8?
(I am using 3.8.10)

--------
Peregrine /opt/summit$ make PythonAPI.3
Setup.sh: llvm-7.0 already installed.
Setup.sh: boost-1.72.0-c7 already installed.
Setup.sh: rpclib-v2.2.1_c2-c7 already installed.
Setup.sh: earcut-v0.12.4-c7 already installed.
Setup.sh: libosmium-v2.13.1-c7 already installed.
Setup.sh: gtest-1.8.1-c7 already installed.
Setup.sh: recast-cdce4e-c7 already installed.
Setup.sh: CARLA version 0.9.8e-6-gaa536ee5-dirty.
Setup.sh: Generating CMake configuration files.
Setup.sh: Success!
BuildLibCarla.sh: Building LibCarla "Client.Release" configuration.
ninja: no work to do.
[0/1] Install the project...
-- Install configuration: "Client"
BuildLibCarla.sh: Success!
BuildPythonAPI.sh: Building Python API for Python 3.
Traceback (most recent call last):
  File "setup.py", line 145, in <module>
    ext_modules=get_libcarla_extensions(),
  File "setup.py", line 33, in get_libcarla_extensions
    linux_distro = platform.dist()[0]  # pylint: disable=W1505
AttributeError: module 'platform' has no attribute 'dist'
make: *** [Util/BuildTools/Linux.mk:89: PythonAPI.3] Error 1

**Comment by LeeYiyuan** [comment]
@PelleNordqvist Since it has been a while, we will be reworking the code to support Ubuntu 20.04 and the newer Python versions in a couple of weeks time -- Python 2 will be stripped for good by then!

We used Python 3.6 to compile -- but it is likely that for 3.8+ you will only need to modify [PythonAPI/carla/setup.py](https://github.com/AdaCompNUS/summit/blob/master/PythonAPI/carla/setup.py) as follows for compile to work: 
- At the top, `import distro`
- On line 33 or 34, change `linux_distro = platform.dist()[0]` to `linux_distro = distro.like()`

 Please let us know if this works!

**Comment by PelleNordqvist** [comment]
Yep, I updated setup.py with your suggestions and sure enough, it works!
So I have a complete build now to play with.
I'm sure I will have more questions later, but for now I am good.
Thanks again!

**Comment by PelleNordqvist** [comment]
Hi again, sorry I closed this too quickly. After I compiled PythonApi, I tried make launch, and there were some new errors;

/opt/summit/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/TrafficSignBase.h(31) : LogCompile: Error: 'ETrafficSignState' does not have a 0 entry! (This is a problem when the enum is initalized by default)
make[1]: *** [Makefile:1080: CarlaUE4Editor] Error 6
make[1]: Leaving directory '/opt/summit/Unreal/CarlaUE4'
make: *** [Util/BuildTools/Linux.mk:10: launch] Error 2

I have fixed these errors as discussed in
https://github.com/carla-simulator/carla/issues/2548
ie by adding
 Null = 0, // Workaround for UE4.24 issue with enums
inside all the affected include files, like so:

UENUM(BlueprintType)
enum class EVehicleInputPriority : uint8
{
 Null = 0, // Workaround for UE4.24 issue with enums
  INVALID = 0u  UMETA(Hidden),
...
}

Now it compiles until I see this:
In file included from /opt/summit/Unreal/CarlaUE4/Plugins/Carla/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/Carla/Module.Carla.cpp:33:
/opt/summit/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/OpenDrive/OpenDriveGenerator.cpp:16:10: fatal error: 'PhysicsEngine/BodySetupEnums.h' file not found
#include "PhysicsEngine/BodySetupEnums.h"

And I think this means my Unreal installation is too new, UE4.26 instead of UE4.24.
Do you agree? I will try to downgrade.

**Comment by LeeYiyuan** [comment]
Yup, we used 4.22 to compile, it will be good if you could use the same version.

**Comment by PelleNordqvist** [comment]
Update; I first tried 4.24 which does not work at all.

Downgrade to 4.22, better. But make launch stops with

> Couldn't launch .../UnrealEngine/Engine/Binaries/Linux/ShaderCompileWorker! Make sure you build ShaderCompileWorker.

Weird, but it is possible to build manually
./Engine/Build/BatchFiles/Linux/Build.sh ShaderCompileWorker Linux Development -verbose

Now after make launch I basically come through the process, the CarlaUE4 editor splash window is visible,
it loads to 96% but then a crash

> [2022.11.08-10.15.22:552][  0]LogCore: Warning: Unable to statfs('/opt/summit/Unreal/CarlaUE4/Saved/Crashes/crashinfo-CarlaUE4-pid-1324168-143F88DB08DAC17A873DB642B3155441/CarlaUE4.log'): errno=2 (No such file or directory)
> Malloc Size=85286 LargeMemoryPoolOffset=923030 

I have seen such crashes before, they were always due to vulcan issues. The workaround was to use opengl instead,
and since this is an old version it should be still possible.

But I am not sure how to set the opengl flag with the "make launch" command.
I used to do CarlaUE4.sh -opengl
but now there is no binary compiled.
`/opt/summit/Util/BuildTools/BuildCarlaUE4.sh --rebuild` succeeds but no binary to be seen.
Perhaps I should wait for your efforts.

P.s. could I perhaps come with a suggestion if this proves difficult; take a look at ES-mini https://github.com/esmini/esmini
which has great opendrive/openscenario support and also lightweight because it uses OSG instead of Unreal.
This is unless you need the sensor capabilities of carla. For me I am fine without, I just want to play with the traffic model.

**Comment by LeeYiyuan** [comment]
@PelleNordqvist Thanks for the detailed investigation as always! Can you check if `sudo apt install vulkan-tools` is installed?  It should allow `./CarlaUE4.sh` to launch without the `-opengl` flag.

For the traffic model, the main logic is actually in a [python script](https://adacompnus.github.io/summit-docs/tutorials/simulating_traffic/) which resides outside of the compiled binary. If you don't require modifying the UE related stuff, running the compiled simulator would work without having to run the entire UE4 editor.

**Comment by PelleNordqvist** [comment]
I checked and vulkan-tools is not installed. Nor is vulkan-utils and some other peripheral stuff.
So I tried `sudo apt install vulkan-*` followed by full rebuild of Unreal + Summit, still same crash.
Now my setup is:
```
vulkan-tools is already the newest version (1.2.131.1+dfsg1-1).
vulkan-utils is already the newest version (1.2.131.1+dfsg1-1).
vulkan-validationlayers is already the newest version (1.2.131.2-1).
vulkan-validationlayers-dev is already the newest version (1.2.131.2-1).
mesa-vulkan-drivers is already the newest version (21.2.6-0ubuntu0.1~20.04.2).
mesa-vulkan-drivers set to manually installed.

```

About Carla, I don't need to edit anything, not with Unreal, not with carla...just play around with the traffic model itself.
I am aware of `<summit_root>/PythonAPI/examples/gamma_crowd.py` (and I was surprised it is hiding in the "examples" folder. This is actually the core of the Summit project?)

`gamma_crowd.py` seems to hold everything to control the traffic, but also it uses Carla API calls so it will not run standalone.
I also noticed there are Sumo Network references via carla API so my initial idea of
a migration to ES-mini would probably not be possible without a lot of work.

It's hard for me to wrap my head around this entangled hybrid `make launch` process in carla.
`make build` succeeds but gives no output.
`make launch-only` crashes.
My best guess is that if `make launch` didn't crash, I would have a CarleUE4.sh server script+binary so
I could run the server with -opengl and then attach the gamma_crowd.py as client.

If you are aware of a method to `make launch -opengl`, I might be able to progress
because I am not sure I want to turn my machine inside out with experimental vulkan drivers.

Thanks again!

**Comment by LeeYiyuan** [comment]
>  (and I was surprised it is hiding in the "examples" folder. This is actually the core of the Summit project?)

The core of SUMMIT would be the extensions we have included in [LibCarla](https://github.com/AdaCompNUS/summit/tree/master/LibCarla/source/carla) to manipulate OSM/SUMO maps for general purposes (for example, [here](https://github.com/AdaCompNUS/magic/blob/master/cpp/src/core/simulations/DriveHard.cpp) we use it in a separate project to learn good macro-actions for self-driving cars on such OSM/SUMO maps). Thus the traffic generation script was categorized as "an example" of using these extensions, through the relevant python bindings :).

> If you are aware of a method to make launch -opengl, I might be able to progress
because I am not sure I want to turn my machine inside out with experimental vulkan drivers.

It seems that there is something we are missing for the build system on 20.04. Let me work on it over the weekend or next, and figure out how to get it to build. If it works, I'll upload a new version which you can use directly without having to compile it on your end.

**Comment by LeeYiyuan** [comment]
@PelleNordqvist We have updated the build instructions for Ubuntu 20.04. If you want to have another go at it, please refer [here](https://adacompnus.github.io/summit-docs/getting_started/building/) and let us know if it works!

Alternatively, you may now download the [built version for distribution](https://adacompnus.github.io/summit-docs/references/releases/). It works on Ubuntu 20.04 + Python 3.8, with Python 2 disabled by default.

**Comment by PelleNordqvist** [comment]
Hi, thanks again for your efforts! 

Quick feedback on your build part:
https://adacompnus.github.io/summit-docs/getting_started/building/
Step 1, typo in 
`libboost1.71-dev-all`
should be 
`libboost1.71-all-dev`

Fixing this, indeed Clang 10.0, Boost 1.71, and Python 3.8 gets installed for me.

Step 3
You probably forgot 'rm' in front of the broken uasset?

`cp CustomAssets/EmptyMap_BuiltData.umap Unreal/CarlaUE4/Content/Carla/Maps/TestMaps/EmptyMap_BuiltData.umap`
I hope you mean .uasset, I don't see an umap here. I changed to
`cp CustomAssets/EmptyMap_BuiltData.uasset Unreal/CarlaUE4/Content/Carla/Maps/TestMaps/EmptyMap_BuiltData.uasset`

After this, build is fine.
`make launch` runs the editor, not interesting to me.
There is no CarlaUE4.sh (why not?) so I just start
`CarlaUE4/Binaries/Linux/CarlaUE4-Linux-Shipping`

I see now an empty sky which is great I guess.
It still stresses the hell out of my 3090 PC which is...less great. But it is Carla :/

Then I start the client in the python examples folder (after installing the requirements.txt)
but it crashes on Sumo deps. Not sure if I am mixing carla versions or something. 
```
python3 gamma_crowd.py 
gamma_crowd.py:1170: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if agent.behavior_type is not -1:
gamma_crowd.py:1178: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if agent.behavior_type is -1:
gamma_crowd.py:1185: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if agent.behavior_type is not -1 or agent.control_velocity is None:
Traceback (most recent call last):
  File "gamma_crowd.py", line 176, in <module>
    carla.SumoNetworkRoutePoint,    
AttributeError: module 'carla' has no attribute 'SumoNetworkRoutePoint'

```

I also tried to run the binary (thankyou for the lite version!)
Here I find the CarlaUE4.sh script. Again an empty sky. Same python sumo dep crash.

**Comment by LeeYiyuan** [comment]
Hi @PelleNordqvist , thanks so much for picking up the errors in the docs! We'll fix that in a bit.

Seeing an empty sky is a good sign that the simulator runs as expected. To spawn the meshes, run `python spawn_meshes.py` in the Python examples folder.

For `make launch` and `CarlaUE4.sh`: `make launch` builds and launches the UE4 editor with CARLA's UE plugin embedded. `CarlaUE4.sh` is a compiled, minified version of this (for distribution) which you will have to compile separately via `make package`. This will build the distribution-version of the simulator into `dist/`.

For the Python examples: since  you are building from source, `make launch` only makes the UE4 editor but not the external libraries. You will need to run `make LibCarla` for the C++ and afterwards `make PythonAPI` for the python wrapper. This will compile the python libraries into `PythonAPI/carla/dist/carla-*.egg`. If you use `make package`, everything including C++ LibCarla and PythonAPI will be built into the output in `dist/`.

Overall, you can think of `make launch`, `make LibCarla` and `make PythonAPI` as build scripts  you would use for "debugging", and you have fine control over which component to build when testing. However, you need to run them one-by-one, separetely. When you are ready, `make package` does everything and packages it nicely into a distribution release.

**Comment by LeeYiyuan** [comment]
@PelleNordqvist For the dependencies crash with the lite version -- it was compiled with Python 3.8, can you check that you are using that exact Python version? Otherwise, you will need to re-compile (`make package`) using your current setup to use the version you have.

**Comment by PelleNordqvist** [comment]
@LeeYiyuan Sorry no progress yet.
Binaries; yes I am using python 3.8. The crash related to 'SumoNetworkRoutePoint' happens even of I don't start the server
so it must be really fundamental.
Nitpick; the tar archive lacks a top folder, it creates a mess when unpacking.

Source code; I totally misread make package as make dist, ie something I only need if I want to redistribute.
But it seems to be really essential.
The first round of `make package` failed but weirdly the 2nd round succeeded. Now I have a Dist folder
so I can run `Dist/CARLA_Shipping_0.9.8f/LinuxNoEditor/CarlaUE4.sh `
but the outcome is the same, I see the sky but gamma crashes
`AttributeError: module 'carla' has no attribute 'SumoNetworkRoutePoint`

another hint:
`python3 meskel_square_ego_vehicle.py 
`crashes with
`AttributeError: module 'carla' has no attribute 'OccupancyMap'
`

< rant >
Not your fault but be aware the `make` command is from the 1970's. https://en.wikipedia.org/wiki/Make_(software)

> In [software development](https://en.wikipedia.org/wiki/Software_development), Make is a [build automation](https://en.wikipedia.org/wiki/Build_automation) tool that automatically [builds](https://en.wikipedia.org/wiki/Software_build) [executable programs](https://en.wikipedia.org/wiki/Executable_program) and [libraries](https://en.wikipedia.org/wiki/Library_(software)) from [source code](https://en.wikipedia.org/wiki/Source_code) by reading [files](https://en.wikipedia.org/wiki/File_(computing)) called Makefiles which specify how to derive the target program.

It means make should never run anything, it should only compile things. Those who introduce 'make launch' etc are breaking a 50 year old standard and generate confusion.
`make launch-only` is just bonkers to me.
< /rant >

**Comment by LeeYiyuan** [comment]
@PelleNordqvist Thanks again for the very detailed investigations. I agree with many of your points; but we decided to adopt the practices from Carla in the name of ... consistency :upside_down_face:

The `carla` python package works on our end, but I think we might have missed out some other case which is raising an issue on yours. Let's try to do this manually:

Under either the lite version or `Dist/CARLA_Shipping_0.9.8f/LinuxNoEditor/`,
- go to`PythonAPI/carla/dist/`. 
- You will find a file named `carla-0.9.8-*.egg`. This contains the compiled (cpython) LibCarla in Python form.
- It is actually a zip folder so you can extract the contents (you can rename it to `carla-0.9.8*-.zip` if needed).
- In the extracted contents, there will be a `carla` folder together with an `EGG-INFO` folder. Open a python shell at this location.
- In the python shell, run the following and let's see what it shows, or if any error pops up:
```
import importlib, inspect
for name, cls in inspect.getmembers(importlib.import_module("carla"), inspect.isclass):
     print(name, cls)
```

In the python shell (at that specific location) you can also play around to debug further: `import carla` and then see if you [can do general stuff with it](https://adacompnus.github.io/summit-docs/references/python_api/).

**Comment by PelleNordqvist** [comment]
Some progress! Your code works, it produces the list below, not sure if it is complete.

Then I realized I am not pointing to the .egg file with PYTHONPATH.
When I add the .egg to the path, I get a new crash;
```
python3 gamma_crowd.py 
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xd
ImportError: numpy.core._multiarray_umath failed to import

```

so i tried a 
`pip3 install numpy --upgrade
`
which leaves me with latest numpy version 1.23.5
and Bingo, now the client works!
When starting with the server, I see sky and falling vehicles. I guess they need a map to drive on :)

So it seems this needs also to be pointed out in the doc:

- eggfile path
- latest numpy
- add road to drive on




```
Actor <class 'carla.libcarla.Actor'>
ActorAttribute <class 'carla.libcarla.ActorAttribute'>
ActorAttributeType <class 'carla.libcarla.ActorAttributeType'>
ActorBlueprint <class 'carla.libcarla.ActorBlueprint'>
ActorList <class 'carla.libcarla.ActorList'>
ActorSnapshot <class 'carla.libcarla.ActorSnapshot'>
ActorState <class 'carla.libcarla.ActorState'>
AttachmentType <class 'carla.libcarla.AttachmentType'>
BlueprintLibrary <class 'carla.libcarla.BlueprintLibrary'>
BoundingBox <class 'carla.libcarla.BoundingBox'>
CityObjectLabel <class 'carla.libcarla.CityObjectLabel'>
Client <class 'carla.libcarla.Client'>
ClientSideSensor <class 'carla.libcarla.ClientSideSensor'>
CollisionEvent <class 'carla.libcarla.CollisionEvent'>
Color <class 'carla.libcarla.Color'>
ColorConverter <class 'carla.libcarla.ColorConverter'>
DVSEvent <class 'carla.libcarla.DVSEvent'>
DVSEventArray <class 'carla.libcarla.DVSEventArray'>
DebugHelper <class 'carla.libcarla.DebugHelper'>
EnvironmentObject <class 'carla.libcarla.EnvironmentObject'>
FakeImage <class 'carla.libcarla.FakeImage'>
FloatColor <class 'carla.libcarla.FloatColor'>
GearPhysicsControl <class 'carla.libcarla.GearPhysicsControl'>
GeoLocation <class 'carla.libcarla.GeoLocation'>
GnssMeasurement <class 'carla.libcarla.GnssMeasurement'>
IMUMeasurement <class 'carla.libcarla.IMUMeasurement'>
Image <class 'carla.libcarla.Image'>
Junction <class 'carla.libcarla.Junction'>
LabelledPoint <class 'carla.libcarla.LabelledPoint'>
Landmark <class 'carla.libcarla.Landmark'>
LandmarkOrientation <class 'carla.libcarla.LandmarkOrientation'>
LandmarkType <class 'carla.libcarla.LandmarkType'>
LaneChange <class 'carla.libcarla.LaneChange'>
LaneInvasionEvent <class 'carla.libcarla.LaneInvasionEvent'>
LaneInvasionSensor <class 'carla.libcarla.LaneInvasionSensor'>
LaneMarking <class 'carla.libcarla.LaneMarking'>
LaneMarkingColor <class 'carla.libcarla.LaneMarkingColor'>
LaneMarkingType <class 'carla.libcarla.LaneMarkingType'>
LaneType <class 'carla.libcarla.LaneType'>
LidarDetection <class 'carla.libcarla.LidarDetection'>
LidarMeasurement <class 'carla.libcarla.LidarMeasurement'>
Light <class 'carla.libcarla.Light'>
LightGroup <class 'carla.libcarla.LightGroup'>
LightManager <class 'carla.libcarla.LightManager'>
LightState <class 'carla.libcarla.LightState'>
Location <class 'carla.libcarla.Location'>
Map <class 'carla.libcarla.Map'>
MapLayer <class 'carla.libcarla.MapLayer'>
MaterialParameter <class 'carla.libcarla.MaterialParameter'>
ObstacleDetectionEvent <class 'carla.libcarla.ObstacleDetectionEvent'>
OpendriveGenerationParameters <class 'carla.libcarla.OpendriveGenerationParameters'>
OpticalFlowImage <class 'carla.libcarla.OpticalFlowImage'>
OpticalFlowPixel <class 'carla.libcarla.OpticalFlowPixel'>
Osm2Odr <class 'carla.libcarla.Osm2Odr'>
Osm2OdrSettings <class 'carla.libcarla.Osm2OdrSettings'>
RadarDetection <class 'carla.libcarla.RadarDetection'>
RadarMeasurement <class 'carla.libcarla.RadarMeasurement'>
Rotation <class 'carla.libcarla.Rotation'>
SemanticLidarDetection <class 'carla.libcarla.SemanticLidarDetection'>
SemanticLidarMeasurement <class 'carla.libcarla.SemanticLidarMeasurement'>
Sensor <class 'carla.libcarla.Sensor'>
SensorData <class 'carla.libcarla.SensorData'>
ServerSideSensor <class 'carla.libcarla.ServerSideSensor'>
TextureColor <class 'carla.libcarla.TextureColor'>
TextureFloatColor <class 'carla.libcarla.TextureFloatColor'>
Timestamp <class 'carla.libcarla.Timestamp'>
TrafficLight <class 'carla.libcarla.TrafficLight'>
TrafficLightState <class 'carla.libcarla.TrafficLightState'>
TrafficManager <class 'carla.libcarla.TrafficManager'>
TrafficSign <class 'carla.libcarla.TrafficSign'>
Transform <class 'carla.libcarla.Transform'>
Vector2D <class 'carla.libcarla.Vector2D'>
Vector3D <class 'carla.libcarla.Vector3D'>
Vehicle <class 'carla.libcarla.Vehicle'>
VehicleControl <class 'carla.libcarla.VehicleControl'>
VehicleDoor <class 'carla.libcarla.VehicleDoor'>
VehicleLightState <class 'carla.libcarla.VehicleLightState'>
VehiclePhysicsControl <class 'carla.libcarla.VehiclePhysicsControl'>
VehicleWheelLocation <class 'carla.libcarla.VehicleWheelLocation'>
Walker <class 'carla.libcarla.Walker'>
WalkerAIController <class 'carla.libcarla.WalkerAIController'>
WalkerBoneControlIn <class 'carla.libcarla.WalkerBoneControlIn'>
WalkerBoneControlOut <class 'carla.libcarla.WalkerBoneControlOut'>
WalkerControl <class 'carla.libcarla.WalkerControl'>
Waypoint <class 'carla.libcarla.Waypoint'>
WeatherParameters <class 'carla.libcarla.WeatherParameters'>
WheelPhysicsControl <class 'carla.libcarla.WheelPhysicsControl'>
World <class 'carla.libcarla.World'>
WorldSettings <class 'carla.libcarla.WorldSettings'>
WorldSnapshot <class 'carla.libcarla.WorldSnapshot'>
bone_transform <class 'carla.libcarla.bone_transform'>
bone_transform_out <class 'carla.libcarla.bone_transform_out'>
vector_of_bones <class 'carla.libcarla.vector_of_bones'>
vector_of_bones_out <class 'carla.libcarla.vector_of_bones_out'>
vector_of_gears <class 'carla.libcarla.vector_of_gears'>
vector_of_ints <class 'carla.libcarla.vector_of_ints'>
vector_of_transform <class 'carla.libcarla.vector_of_transform'>
vector_of_vector2D <class 'carla.libcarla.vector_of_vector2D'>
vector_of_wheels <class 'carla.libcarla.vector_of_wheels'>

```

**Comment by PelleNordqvist** [comment]
Update:
`python3 spawn_meshes.py `
fixes the map. It looks very promising.

Now time for the real work!

![summit](https://user-images.githubusercontent.com/15340912/204562543-4711127e-64e7-4d5a-b037-56106f689d49.jpg)
(url)

**Comment by LeeYiyuan** [comment]
We made it!

Thank you so much again for following through, @PelleNordqvist :) We definitely have something more up-to-date now.

I'll update the docs in a bit for the final touch ups!
